routes/web.php
<?php
Route::group(['middleware' => 'incognito'], function() {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('pages/{page}',['as' => 'the-le',function ($page) {
        //if(in_array($page, ['cong-thuc-kem-dinh', 'qua-tang', 'the-le']))
        return view('frontend.pages.' . $page);
    }]);
    Route::get('/tin-tuc', 'NewsController@index')->name('news');
    Route::get('/{alias?}nc{id}.html', 'NewsController@category')->where('id', '[0-9]+');
    Route::get('/{alias?}nt{id}.html', 'NewsController@tag')->where('id', '[0-9]+');
    Route::get('/{alias?}n{id}.html', 'NewsController@show')->where('id', '[0-9]+')->name('news');

    Route::get('/profile/{userId}', 'SubmitController@profile')->name('profile');
    Route::get('bai-du-thi/share', 'SubmitController@share');
    Route::get('bai-du-thi/vote', 'SubmitController@vote');
    Route::get('bai-du-thi/checkUser', 'SubmitController@checkUser');
    Route::resource('bai-du-thi', 'SubmitController');
    Route::get('tham-gia-cuoc-thi', 'SubmitController@create');

    Route::get('news', 'NewsController@index');
    Route::resource('lien-he', 'ContactController');
    Route::resource('comments', 'CommentsController');
    Route::resource('faq', 'FaqController');
    Route::post('upload', 'UploadController@upload');
    Route::post('upload/compress', 'UploadController@uploadCompressImage');
});

Route::group(['middleware' => 'auth', 'prefix'=> 'member'], function () {
    Route::get('', 'MemberController@index');
    Route::get('{id}/edit', 'MemberController@edit');
    Route::post('{id}', 'MemberController@update');
    Route::get('{id}/password', 'MemberController@password');
    Route::post('{id}/password', 'MemberController@password');
    Route::get('posts', 'MemberController@posts');
    Route::get('transactions', 'MemberController@posts');
});

//Custom Error
Route::get('404.htm', function () {return view('errors.404_');});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@showLoginForm');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::post('auth/fblogin', 'Auth\AuthController@fbLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
Route::post('password/reset', 'Auth\PasswordController@postReset');

// Admin
Route::auth();
Route::group(['middleware' => 'admin', 'prefix'=> 'admin', 'namespace' => 'Admin'], function () {

    Route::resource('', 'DashboardController');

    Route::resource('submit_category_items', 'SubmitCategoryItemsController');
    Route::resource('submit_category', 'SubmitCategoryController');

    Route::resource('demo', 'DemoController');
    Route::resource('demo_category', 'DemoCategoryController');
    Route::resource('demo_category_items', 'DemoCategoryItemsController');

    Route::resource('faq', 'FaqController');

    Route::resource('contact', 'ContactController');

    Route::resource('news', 'NewsController');
    Route::resource('videos', 'VideosController');
    Route::resource('kol', 'KolController');
    Route::resource('pages', 'PagesController');

    Route::resource('media', 'MediaController');
    Route::resource('tags', 'TagsController');

    Route::get('user/update-password',['as' => 'user.updatePassword',function () { return view('admin.user.update-password'); }]);
    Route::post('user/update-password', ['as' => 'user.updatePassword' , 'uses' => 'UserController@updatePassword']);

    Route::get('login_as_this_member/{id}', ['as' => 'user.loginAsThisMember' , 'uses' => 'UserController@loginAsThisMember']);

    Route::resource('user', 'UserController');

    Route::group(['middleware' => 'App\\Http\\Middleware\\AdminSystemMiddleware'], function () {
        Route::resource('menu', 'MenuController');
        Route::post('user/update-fb-avatar', 'UserController@updateFbAvatar');
        Route::resource('config', 'ConfigController');
    });
});

/*Route::get('media/{year}-{month}/{date}/{name}', function($year, $month, $date, $name)
{
    $filePath =  "media/{$year}-{$month}/{$date}/{$name}";
    if(!App\Helper\FileHelper::hasFile($filePath)) {
        return Response::make("File does not exist.", 404);
    }

    $fileContents = App\Helper\FileHelper::getFile($filePath);
    $mimeType = App\Helper\FileHelper::mimeType($filePath);
    return Response::make($fileContents, 200, array('Content-Type' => $mimeType));
});*/

// Incognito
Route::get('/users/{id}/incognito', 'UserController@incognito');
Route::get('/users/incognito/logout', 'UserController@stopIncognito');

app/Models/Tags.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Illuminate\Support\Facades\Input;

use DB;
use phpDocumentor\Reflection\DocBlock\Tag;

class Tags extends Model
{
    public $timestamps = false;
    public $table = 'tags';
    //
    protected $fillable = [
        'title',
        'alias',
        'description',
        'seo_title',
        'seo_description',
        'is_hot',
        'status'
    ];

    public function scopeSearch($query, $keyword=null)
    {
        if($keyword){
            $query->where('title', 'like', '%'.$keyword.'%');
        }
        
        return $query;
    }

    public static function loadTags($newsId){
        $data = [];
        // Get tags_id
        $tags = DB::table('news_tags')->where('news_id', $newsId)->pluck('news_id', 'tags_id');
        if(count($tags)){
            $items = Tags::whereIn('id', array_keys($tags))->select('id', 'title', 'alias')->get();
            return $items;
        }

        return $data;
    }

    public static function saveTags($tags, $newsId){
        // Delete first
        DB::table('news_tags')->where('news_id', $newsId)->delete();
        $tags = explode(',', $tags);

        foreach ($tags as $tag){
            $tag = trim($tag);
            if(empty($tag)) continue;
            
            if(strpos($tag, ':') !== false){
                $tag = explode(':', $tag);
                DB::insert('insert into news_tags (news_id, tags_id) values (?, ?)', [$newsId, $tag[1]]);
            }else{
                $item = new Tags();
                $item = $item::create(['title' => $tag, 'alias' => $tag]);
                if($item){
                    DB::insert('insert into news_tags (news_id, tags_id) values (?, ?)', [$newsId, $item->id]);
                }
            }
        }
    }

    public static function removeTags($newsId){
        DB::table('news_tags')->where('news_id', $newsId)->delete();
    }

    public function setAliasAttribute($alias){
        $this->attributes['alias'] = \App\Helper\StringHelper::removeSign($this->attributes['title']);
    }

    public static function boot()
    {
        parent::boot();
    }

    public static function setStatus($id, $value){
        $item = Tags::findOrFail($id);
        $item->status = $value;
        $item->save();
    }
}

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use Illuminate\Support\Facades\Response;
use App\Http\Controllers\Controller;
use App\Helper\RequestHelper;

use Session;
use App\Models\Tags;

class TagsController extends Controller
{
    public $view = 'admin.tags';
    public $link = 'admin/tags';

    public function index(Request $request){
        if($request->status != ''){
            Tags::setStatus($request->id, $request->status);
        }

        $limit = RequestHelper::getRequestSession('limit', 20);

        $tagsModel = new Tags();
        if($request->ajax){
            $data = [];
            $items = $tagsModel->search($request->keyword)->select('id', 'title')->limit(1000)->get();
            foreach ($items as $item){
                $data[] = $item->title.' :'.$item->id;
            }
            return Response::json(
                $data
            );
        }

        $news = $tagsModel->search($request->keyword)->paginate($limit);

        return view($this->view.'.index')->with('news', $news);
    }

    public function create(){

        return view($this->view.'.create');
    }

    public function edit($id){

        //Tìm article thông qua mã id tương ứng
        $news = Tags::findOrFail($id);

        // Gọi view edit.blade.php hiển thị bải viết
        return view($this->view.'.edit', compact('news'));
    }

    public function destroy($id){
        $news = Tags::find($id);
        $news->delete();

        Session::flash('message', 'Xóa thành công!');
        return redirect($this->link);
    }

    /**
     * Update record
     *
     * @param int $id
     * @param CheckNewsRequest $request
     * @return Ambigous
     */
    public function update($id, Request $request){

        $data = $request->all();
        $news = Tags::findOrFail($id);
        $news->update($data);

        Session::flash('message', 'Cập nhật thành công!');
        return redirect($this->link);
    }

    /**
     * Save news
     *
     */
    public function store(Request $request){

        $data = $request->all();
        $news = new Tags();
        $news::create($data);

        Session::flash('message', 'Tạo mới thành công!');
        return redirect($this->link);
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.admin')

@section('breadcrum')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Quản lý Tags
		<small>Tags</small>
	</h1>
	<ol class="breadcrumb hidden">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>
@stop

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box box-info">
			<div class="box-header with-border">
				<h3 class="box-title">Thêm / Sửa thông tin</h3>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			{!! Form::open( ['url' => 'admin/tags', 'class' => 'form-horizontal', 'name'=>'uploadform', 'files'=>true] ) !!}
			<div class="box-body" style="padding: 5px;">
				<ul class="nav nav-tabs" role="tablist">
					<li role="presentation" class="active"><a href="#vn" aria-controls="vn" role="tab" data-toggle="tab">Nội dung</a></li>
					<li role="presentation" class="hidden"><a href="#en" aria-controls="en" role="tab" data-toggle="tab">Tiếng Anh</a></li>
				</ul>

				<div class="tab-content">
					<div role="tabpanel" class="tab-pane active" id="vn">
						<div class="form-group">
							<label class="col-sm-2 control-label">Tiêu đề</label>
							<div class="col-sm-10">
								{!! Form::text('title', '', array('class' => 'form-control')) !!}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label" for="inputPassword3">Mô tả đầy đủ</label>
							<div class="col-sm-10">
								{!! Form::textarea('description', '', array('class' => 'form-control', 'id' => 'editor11', 'rows' => 3)) !!}
							</div>
						</div>
						<div class="form-group hidden">
							<label class="col-sm-2 control-label" for="inputPassword3"></label>
							<div class="col-sm-10">
								<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#mediaModal">
									<i class="fa fa-cloud-upload"></i> Chèn ảnh, File
								</button>
							</div>
						</div>
					</div>

					<div role="tabpanel" class="tab-pane hidden" id="en">
						<div class="form-group">
							<label class="col-sm-2 control-label">Tiêu đề</label>
							<div class="col-sm-10">
								{!! Form::text('title_en', '', array('class' => 'form-control')) !!}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label" for="inputPassword3">Mô tả đầy đủ</label>
							<div class="col-sm-10">
								{!! Form::textarea('fulltext_en', '', array('class' => 'form-control', 'id' => 'editor2', 'rows' => 3)) !!}
							</div>
						</div>
					</div>
				</div>
				<!-- /.box-body -->
			</div>
			<div class="box-footer">
				<div class="col-sm-2"></div>
				<div class="col-sm-10">
					<button class="btn btn-primary" type="submit"><i class="fa fa-check-circle"></i> Hoàn tất</button>
					<a class="btn btn-default" href="<?php echo URL::to('/admin/tags');?>">Quay lại</a>
				</div>
			</div>
			<!-- /.box-footer -->
			{!! Form::close() !!}
		</div>
	</div>
</div>

@stop

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.admin')

@section('breadcrum')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Quản lý Tags
		<small>Tags</small>
	</h1>
	<ol class="breadcrumb hidden">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>
@stop

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box box-info">
			<div class="box-header with-border">
				<h3 class="box-title">Thêm / Sửa thông tin</h3>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			{!! Form::model($news,[ 'method' => 'PATCH', 'action' => ['Admin\\TagsController@update', $news->id], 'name'=>'uploadform', 'class' => 'form-horizontal', 'files'=>true ]) !!}
			<div class="box-body" style="padding: 5px;">
				<ul class="nav nav-tabs" role="tablist">
					<li role="presentation" class="active"><a href="#vn" aria-controls="vn" role="tab" data-toggle="tab">Nội dung</a></li>
					<li role="presentation" class="hidden"><a href="#en" aria-controls="en" role="tab" data-toggle="tab">Tiếng Anh</a></li>
				</ul>

				<div class="tab-content">
					<div role="tabpanel" class="tab-pane active" id="vn">
						<div class="form-group">
							<label class="col-sm-2 control-label">Tiêu đề</label>
							<div class="col-sm-10">
								{!! Form::text('title', $news->title, array('class' => 'form-control')) !!}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label" for="inputPassword3">Mô tả đầy đủ</label>
							<div class="col-sm-10">
								{!! Form::textarea('description', $news->description, array('class' => 'form-control', 'id' => 'editor11', 'rows' => 3)) !!}
							</div>
						</div>
						<div class="form-group hidden">
							<label class="col-sm-2 control-label" for="inputPassword3"></label>
							<div class="col-sm-10">
								<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#mediaModal">
									<i class="fa fa-cloud-upload"></i> Chèn ảnh, File
								</button>
							</div>
						</div>
					</div>

					<div role="tabpanel" class="tab-pane hidden" id="en">
						<div class="form-group">
							<label class="col-sm-2 control-label">Tiêu đề</label>
							<div class="col-sm-10">
								{!! Form::text('title_en', $news->title_en, array('class' => 'form-control')) !!}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label" for="inputPassword3">Mô tả đầy đủ</label>
							<div class="col-sm-10">
								{!! Form::textarea('fulltext_en', $news->fulltext_en, array('class' => 'form-control', 'id' => 'editor2', 'rows' => 3)) !!}
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<div class="col-sm-2"></div>
				<div class="col-sm-10">
					<button class="btn btn-primary" type="submit"><i class="fa fa-check-circle"></i>   Hoàn tất</button>
					<a class="btn btn-default" href="<?php echo URL::to('/admin/tags');?>">Quay lại</a>
				</div>
			</div>
			<!-- /.box-footer -->
			{!! Form::close() !!}

		</div>
	</div>
</div>

@stop

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.admin')

@section('breadcrum')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Quản lý Tags
		<small>Tags</small>
	</h1>
	<ol class="breadcrumb hidden">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>
@stop

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header hidden">
				<h3 class="box-title">Data Table With Full Features</h3>
			</div>
			<!-- /.box-header -->
			{!! Form::open( ['url' => 'admin/tags', 'method' => 'get'] ) !!}
			<div class="box-body">
				<div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
					<div class="row">
						<div class="col-sm-6">
							<div id="example1_filter" class="dataTables_filter" style="text-align:left">
								<label><input type="search" class="form-control input-sm" value="{{ app('request')->input('keyword') }}" placeholder="Từ khóa tìm kiếm" name="keyword"></label>
								<button class="btn btn-sm btn-primary"><i class="fa fa-fw fa-search"></i> Tìm kiếm</button>
							</div>
						</div>
						<div class="col-sm-6 text-right">
							@can('admin.manage', 'tags-edit')
							<a class="btn btn-success" href="<?php echo URL::to('/admin/tags/create');?>"><i class="fa fa-plus-circle"></i> Thêm mới</a>
							@endcan
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-bordered table-striped dataTable" id="example1" role="grid" aria-describedby="example1_info">
								<thead>
								<tr role="row" class="text-center">
									<th class="text-center" style="padding-right: 10px;">STT</th>
									<th class="sorting_asc1" aria-sort="ascending">Tiêu đề</th>
									<th class="sorting1 text-center">Mô tả</th>
									<th class="sorting1 text-center">Trạng thái</th>
									<th class="sorting1 text-center">ID</th>
									<th class="sorting1 text-center">...</th>
								</tr>
								</thead>
								<tbody>
								@foreach( $news as $k => $item )
									<tr role="row" class="even">
										<td class="text-center">{{$k+1}}</td>
										<td>
											@can('admin.manage', 'tags-edit')<a href="<?php echo URL::to('/admin/tags/'.$item->id);?>/edit">{{$item->title}}</a>
												@else
												{{$item->title}}
											@endcan
										</td>
										<td>{{ $item->description }}</td>
										<td class="text-center">
											@can('admin.manage', 'tags-status')<a href="{{ url('admin/tags?id='.$item->id.'&status='.( ($item->status) ? 0 : 1 )) }}">
											{!! \App\Helper\StringHelper::stateStatus($item->status)  !!}</a>
											@else
												{!! \App\Helper\StringHelper::stateStatus($item->status)  !!}
											@endcan
										</td>
										<td class="text-center">{{$item->id}}</td>
										<td class="text-center">
											@can('admin.manage', 'tags-edit')<a class="btn btn-success btn-xs" href="<?php echo URL::to('/admin/tags/'.$item->id);?>/edit"><i class="fa fa-pencil"></i> Sửa</a>@endcan
											@can('admin.manage', 'tags-delete')<a onclick="return deleteItem({{$item->id}});" class="btn btn-danger btn-xs" href="#"><i class="fa fa-trash"></i> Xóa</a>@endcan
										</td>
									</tr>
								@endforeach
								</tbody>
								<tfoot class="hidden">
								<tr>
									<th rowspan="1" colspan="1">Rendering engine</th>
									<th rowspan="1" colspan="1">Browser</th>
									<th rowspan="1" colspan="1">Platform(s)</th>
									<th rowspan="1" colspan="1">Engine version</th>
									<th rowspan="1" colspan="1">CSS grade</th>
								</tr>
								</tfoot>
							</table>
						</div>
					</div>
					<div class="row"><br/>
						<div class="col-sm-5">
							<div class="dataTables_length" id="example1_length">
								<label>Hiển thị <select onchange="this.form.submit();" name="limit" class="form-control input-sm">
										<option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> mục</label>
							</div>
							<div class="dataTables_info hidden" id="example1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
						</div>
						<div class="col-sm-7">
							<div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
								{!! $news->appends(array('keyword' => app('request')->input('keyword')))->links() !!}
							</div>
						</div>
					</div>
				</div>
			</div>
		{!! Form::close() !!}
			<!-- /.box-body -->
		</div>
	</div>
</div>

<div class="hidden">
	<form action="{{ URL::route('tags.destroy', '') }}" id="form_delete" method="POST">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
	</form>
</div>
<script type="text/javascript">
	function deleteItem(id){
		if ( confirm('Bạn có chắc chắn muốn xóa?') ) {
			$('#form_delete').attr('action', $('#form_delete').attr('action') + "/" + id);
			$('#form_delete').submit();
		}
		return false;
	}
</script>
@stop