routes/web.php
<?php
Route::group(['middleware' => 'incognito'], function() {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('pages/{page}',['as' => 'the-le',function ($page) {
        //if(in_array($page, ['cong-thuc-kem-dinh', 'qua-tang', 'the-le']))
        return view('frontend.pages.' . $page);
    }]);
    Route::get('/tin-tuc', 'NewsController@index')->name('news');
    Route::get('/{alias?}nc{id}.html', 'NewsController@category')->where('id', '[0-9]+');
    Route::get('/{alias?}nt{id}.html', 'NewsController@tag')->where('id', '[0-9]+');
    Route::get('/{alias?}n{id}.html', 'NewsController@show')->where('id', '[0-9]+')->name('news');

    Route::get('/profile/{userId}', 'SubmitController@profile')->name('profile');
    Route::get('bai-du-thi/share', 'SubmitController@share');
    Route::get('bai-du-thi/vote', 'SubmitController@vote');
    Route::get('bai-du-thi/checkUser', 'SubmitController@checkUser');
    Route::resource('bai-du-thi', 'SubmitController');
    Route::get('tham-gia-cuoc-thi', 'SubmitController@create');

    Route::get('news', 'NewsController@index');
    Route::resource('lien-he', 'ContactController');
    Route::resource('comments', 'CommentsController');
    Route::resource('faq', 'FaqController');
    Route::post('upload', 'UploadController@upload');
    Route::post('upload/compress', 'UploadController@uploadCompressImage');
});

Route::group(['middleware' => 'auth', 'prefix'=> 'member'], function () {
    Route::get('', 'MemberController@index');
    Route::get('{id}/edit', 'MemberController@edit');
    Route::post('{id}', 'MemberController@update');
    Route::get('{id}/password', 'MemberController@password');
    Route::post('{id}/password', 'MemberController@password');
    Route::get('posts', 'MemberController@posts');
    Route::get('transactions', 'MemberController@posts');
});

//Custom Error
Route::get('404.htm', function () {return view('errors.404_');});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@showLoginForm');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::post('auth/fblogin', 'Auth\AuthController@fbLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
Route::post('password/reset', 'Auth\PasswordController@postReset');

// Admin
Route::auth();
Route::group(['middleware' => 'admin', 'prefix'=> 'admin', 'namespace' => 'Admin'], function () {

    Route::resource('', 'DashboardController');

    Route::resource('submit_category_items', 'SubmitCategoryItemsController');
    Route::resource('submit_category', 'SubmitCategoryController');

    Route::resource('demo', 'DemoController');
    Route::resource('demo_category', 'DemoCategoryController');
    Route::resource('demo_category_items', 'DemoCategoryItemsController');

    Route::resource('faq', 'FaqController');

    Route::resource('contact', 'ContactController');

    Route::resource('news', 'NewsController');
    Route::resource('videos', 'VideosController');
    Route::resource('kol', 'KolController');
    Route::resource('pages', 'PagesController');

    Route::resource('media', 'MediaController');
    Route::resource('tags', 'TagsController');

    Route::get('user/update-password',['as' => 'user.updatePassword',function () { return view('admin.user.update-password'); }]);
    Route::post('user/update-password', ['as' => 'user.updatePassword' , 'uses' => 'UserController@updatePassword']);

    Route::get('login_as_this_member/{id}', ['as' => 'user.loginAsThisMember' , 'uses' => 'UserController@loginAsThisMember']);

    Route::resource('user', 'UserController');

    Route::group(['middleware' => 'App\\Http\\Middleware\\AdminSystemMiddleware'], function () {
        Route::resource('menu', 'MenuController');
        Route::post('user/update-fb-avatar', 'UserController@updateFbAvatar');
        Route::resource('config', 'ConfigController');
    });
});

/*Route::get('media/{year}-{month}/{date}/{name}', function($year, $month, $date, $name)
{
    $filePath =  "media/{$year}-{$month}/{$date}/{$name}";
    if(!App\Helper\FileHelper::hasFile($filePath)) {
        return Response::make("File does not exist.", 404);
    }

    $fileContents = App\Helper\FileHelper::getFile($filePath);
    $mimeType = App\Helper\FileHelper::mimeType($filePath);
    return Response::make($fileContents, 200, array('Content-Type' => $mimeType));
});*/

// Incognito
Route::get('/users/{id}/incognito', 'UserController@incognito');
Route::get('/users/incognito/logout', 'UserController@stopIncognito');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\InputHelper;
use App\Models\News;
use Illuminate\Http\Request;
use App\Helper\FileHelper;
use App\Http\Requests;
use Carbon\Carbon;
use App\Http\Controllers\Controller;
use App\Http\Requests\CheckUserRequest;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Input;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Redirect;
use App\Helper\StringHelper;
use Maatwebsite\Excel\Facades\Excel as Excel;
use App\Helper\RequestHelper;

use Session;
use DB;
use File;
use Auth;
use App\Models\User;
use App\Models\Submit;

class UserController extends Controller
{
    public $view = 'admin.user';
    public $link = 'admin/user';

    public function index(Request $request)
    {
        $user = Auth::user();
        if ($request->action == 'export') {
            return $this->export();
        }
        $group = (int)RequestHelper::getRequestSession('group', '');
        $keyword = Input::get('keyword');
        $userId = Input::get('user_id', 0);
        $promotion = Input::get('promotion');

        $users = User::search($group, $keyword, $promotion)->where('group', '>=', $user->group)->orderBy('id', 'DESC');
        if($userId){
            $users->where('id', $userId);
        }
        $users = $users->paginate(20);

        if ($request->ajax()) {
            $users = User::search($group, $keyword, $promotion)->orderBy('id', 'DESC')->limit(20)->get();
            return Response::json($users);
        }

        return view($this->view . '.index', compact('group', 'keyword', 'promotion'))
            ->with('news', $users)
            ->with('groups', User::getUserGroups());
    }

    public function create()
    {
        /*$newsCategory = new NewsCategory();*/
        $newsCats = [];//$newsCategory->getCategoryTree(0, '');

        return view($this->view . '.create', compact('newsCats'));
    }

    public function edit($id)
    {
        /*$newsCategory = new NewsCategory();*/
        $newsCats = [];//$newsCategory->getCategoryTree(0, '');

        //Tìm article thông qua mã id tương ứng
        $news = User::findOrFail($id);
        $news->permission = explode("\n", $news->permission);

        // Gọi view edit.blade.php hiển thị bải viết
        return view($this->view . '.edit', compact('news', 'newsCats'));
    }

    public function destroy($id)
    {
        $news = User::find($id);
        if ($news->image) {
            // Delete image
            @unlink(StringHelper::getUploadPath($news->image));
        }

        $news->delete();

        Session::flash('message', 'Xóa thành công!');
        return redirect($this->link);
    }

    /**
     * Update record
     *
     * @param int $id
     * @param CheckNewsRequest $request
     * @return Ambigous
     */
    public function update($id, CheckUserRequest $request)
    {
        $currUser = Auth::user();

        $data = $request->all();
        $user = User::findOrFail($id);
        $response = array(
            'code' => 1,
            'message' => 'Success update user profile'
        );

        if (!empty($data['email']) && User::checkEmail($data['email'], $id)) {
            if($request->ajax()) {
                $response['code'] = 0;
                $response['message'] = 'Fail update user profile';
                return Response::json($response);
            }
            return Redirect::back()->withInput()->withErrors(array('email' => 'Email: "' . $request->email . '" đã tồn tại. Vui lòng chọn email khác.'));
        }

        if (Input::file()) {
            $image = Input::file('image_upload');
            $filename = time() . '.' . $image->getClientOriginalExtension();

            $filePath = 'uploads/avatar/' . $filename;

            Image::make($image->getRealPath())->resize(200, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(StringHelper::getUploadPath($filePath));

            if ($user->avatar) {
                // Delete image
                @unlink(StringHelper::getUploadPath($user->avatar));
            }
            $data['avatar'] = $filePath;
        }

        if ($request->password_new) {
            $data['password'] = Hash::make(trim($data['password_new']));
        }

        $data['group'] = $data['group'] >= $currUser->group ? $data['group'] : $currUser->group;

        $user->update($data);
        //User::setPermission($id, $request);

        if(!$request->ajax()) {
            Session::flash('message', 'Cập nhật thành công!');
            if ($request->action == 'save') {
                return redirect('admin/user');
            } else {
                return redirect('admin/user/' . $user->id . '/edit');
            }
        } else {
            $response['user'] = $user;
            return Response::json($response);
        }
    }

    /**
     * Save news
     *
     */
    public function store(CheckUserRequest $request)
    {
        $currUser = Auth::user();
        $data = $request->all();

        if (User::checkEmail($request->email)) {
            return Redirect::back()->withInput()->withErrors(array('email' => 'Email: "' . $request->email . '" đã tồn tại. Vui lòng chọn email khác.'));
        }

        if (Input::file()) {
            $image = Input::file('image_upload');
            $filename = time() . '.' . $image->getClientOriginalExtension();

            $filePath = 'uploads/avatar/' . $filename;

            Image::make($image->getRealPath())->resize(200, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(StringHelper::getUploadPath($filePath));

            $data['avatar'] = $filePath;
        }
        if ($request->password_new) {
            $data['password'] = Hash::make(trim($data['password_new']));
        }

        $data['group'] = $data['group'] >= $currUser->group ? $data['group'] : $currUser->group;

        $news = new User();
        $news = $news::create($data);
        //User::setPermission($news->id, $request);

        Session::flash('message', 'Tạo mới thành công!');
        if ($request->action == 'save') {
            return redirect('admin/user');
        } else {
            return redirect('admin/user/' . $news->id . '/edit');
        }
    }

    public function export()
    {
        $groups = User::getUserGroups();
        $page = 1;
        $totalPage = round(User::count() / 10000) + 1;

        for ($i = 1; $i <= $totalPage; $i++) {
            Excel::create('Kenh14_' . $i, function ($excel) use ($groups, $page, $totalPage) {

                Input::merge(['page' => $page]);
                $items = User::search()->orderBy('id', 'DESC')->paginate(10000);

                $excel->sheet('Users_' . $page, function ($sheet) use ($groups, $items, $page) {
                    $sheet->row(1, array(
                        'STT', 'Họ và tên', 'Tuổi', 'Số ĐT', 'Email', 'FB ID', 'Địa chỉ', 'Nhóm', 'Ngày đăng ký'
                    ));
                    $sheet->cell('A1:E1', function ($cells) {
                        $cells->setFontWeight('bold');
                    });
                    $sheet->freezeFirstRow();

                    if ($items && count($items)) {
                        foreach ($items as $k => $item) {
                            $sheet->row($k + 2, array(
                                10000 * ($page - 1) + $k + 1,
                                $item->name,
                                Carbon::parse($item->birthday)->age,
                                $item->mobile,
                                $item->email,
                                $item->facebook_id . ' ',
                                $item->address,
                                (isset($groups[$item->group])) ? $groups[$item->group] : '',
                                date('d-m-Y', strtotime($item->created_at))
                            ));
                        }
                    }
                });

            })->store('xls', public_path('uploads/content'));

            $page++;
        }

        $html = [];
        for ($i = 1; $i <= $totalPage; $i++) {
            $link = url('uploads/content/Kenh14_' . $i . '.xls');
            $html[] = '<a href="' . $link . '">' . $link . '</a>';
        }

        return join('<br/>', $html);
    }

    public function updateFbAvatar(Request $request)
    {
        $users_id = $request->get('users');
        $errors = [];
        $flag_avatar = true;

        foreach ($users_id as $i => $item) {
            $user = User::where('id', '=', $item)->where('group', '>', '2')->first();

            if ($user) {
                $flag_avatar = true;
                if ($user->avatar) {
                    if (File::exists(StringHelper::getUploadPath($user->avatar))) {
                        $flag_avatar = false;
                    }
                }

                if ($flag_avatar) {
                    // Save image into server
                    $avatar = "http://graph.facebook.com/" . $user->facebook_id . "/picture?type=large";
                    $saved = @Image::make($avatar)->save(public_path('uploads/avatar/' . $user->id . '.jpg'));
                    if ($saved) {
                        $avatar = 'uploads/avatar/' . $user->id . '.jpg';
                        $user->update(['avatar' => $avatar]);

                        // Generation image share fb
                        $submit = Submit::where('user_id', $item)->first();
                        if ($submit) {
                            $catClassFolder = StringHelper::getColorCategories()[(($submit->cat_id) - 1)][3];
                            try {
                                FileHelper::createImageSubmit(htmlspecialchars_decode($submit->introtext), $user->name, $user->avatar, $submit->id, $submit->image, $catClassFolder);
                            } catch (Exception $e) {

resources/views/admin/user/create.blade.php
@extends('admin.layouts.admin')

@section('breadcrum')
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Quản lý Thành viên
			<small>Thành viên</small>
		</h1>
		<ol class="breadcrumb hidden">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Dashboard</li>
		</ol>
	</section>
@stop

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<h3 class="box-title">Thêm / Sửa thông tin</h3>
				</div>
				<!-- /.box-header -->
				<!-- form start -->
				{!! Form::open( ['url' => 'admin/user', 'class' => 'form-horizontal', 'files'=>true] ) !!}
				<div class="box-body">
					<div class="form-group">
						<label class="col-sm-2 control-label">Nhóm</label>
						<div class="col-sm-10">
							{!! Form::select('group', \App\Models\User::getUserGroups(), old('group', 3), array('class'=>'form-control',  'style'=>'width:200px', 'onchange'=>'showGroup(this.value);')) !!}
						</div>
					</div>
					<div class="form-group group group2 hidden">
						<label class="col-sm-2 control-label">Phân quyền</label>
						<div class="col-sm-10">
							Chức năng này sẽ hiển thị khi bạn lưu xong thông tin người dùng
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Họ và tên</label>
						<div class="col-sm-10">
							{!! Form::text('name', old('name'), array('class' => 'form-control')) !!}
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Email</label>
						<div class="col-sm-10">
							{!! Form::text('email', old('email'), array('class' => 'form-control')) !!}
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Điện thoại</label>
						<div class="col-sm-10">
							{!! Form::text('mobile', old('mobile'), array('class' => 'form-control')) !!}
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Ảnh</label>
						<div class="col-sm-10">
							{!! Form::file('image_upload') !!}
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Trạng thái</label>
						<div class="col-sm-10">
							{!! Form::select('status', array(1=>'Hoạt động', 0=>'Banned'), old('status'), array('class'=>'form-control')) !!}
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Mật khẩu</label>
						<div class="col-sm-10">
							<div class="password">
								{!! Form::text('password_new', old('password_new'), array('class' => 'form-control', 'placeholder' => 'Nhập mật khẩu mới')) !!}
							</div>
						</div>
					</div>
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<div class="col-sm-2"></div>
					<div class="col-sm-10">
						<button class="btn btn-primary" onclick="$('#action').val('save');" type="submit"><i class="fa fa-check-circle"></i>   Lưu & Quay lại</button>
						<button class="btn btn-primary" onclick="$('#action').val('apply');" type="submit"><i class="fa fa-save"></i> Lưu</button>
						<a class="btn btn-default" href="<?php echo URL::to('admin/user');?>">Quay lại</a>
					</div>
				</div>
				<!-- /.box-footer -->
				<input type="hidden" name="action" id="action" value="save">
				{!! Form::close() !!}

				<script>
					function showGroup(groupId){
						$('.group').addClass('hidden');
						$('.group' + groupId).removeClass('hidden');
					}
				</script>
			</div>
		</div>
	</div>

@stop

resources/views/admin/user/index.blade.php
@extends('admin.layouts.admin')

@section('breadcrum')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Quản lý Thành viên
		<small>Thành viên</small>
	</h1>
	<ol class="breadcrumb hidden">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>
@stop

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header hidden">
				<h3 class="box-title">Data Table With Full Features</h3>
			</div>
			<!-- /.box-header -->
			{!! Form::open( ['url' => 'admin/user', 'method' => 'get'] ) !!}
			<div class="box-body">
				<div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
					<div class="row">
						<div class="col-sm-8">
							<div id="example1_filter" class="dataTables_filter" style="text-align:left">
								{!! Form::select('group', $groups, $group, array('class'=>'form-control', 'onchange' => 'this.form.submit()')) !!}
								<label><input type="search" class="form-control input-sm" value="{{ $keyword }}" placeholder="Từ khóa tìm kiếm" name="keyword"></label>
								<label><input type="search" class="form-control input-sm" value="{{ $promotion }}" placeholder="Mã khuyến mại" name="promotion"></label>
								<button class="btn btn-sm btn-primary"><i class="fa fa-fw fa-search"></i> Tìm kiếm</button>
							</div>
						</div>
						<div class="col-sm-4 text-right">
							<a class="btn btn-primary" href="<?php echo URL::to('/admin/user?action=export');?>"><i class="fa fa-cloud-download"></i> Excel</a>
							<a class="btn btn-success" href="<?php echo URL::to('/admin/user/create');?>"><i class="fa fa-plus-circle"></i> Thêm mới</a>
							<a class="btn btn-success hidden" href="#" onclick="update_avatar_fb(this); return false;"><i class="fa fa-chain"></i> Update avatar FB</a>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-bordered table-striped dataTable" id="tableUser" role="grid" aria-describedby="example1_info">
								<thead>
								<tr role="row" class="text-center">
									<th class="text-center" style="padding-right: 10px;">STT</th>
									<th class="sorting_asc1" aria-sort="ascending">Họ và tên</th>
									<th class="sorting1 text-center">Phân quyền</th>
									<th class="sorting1 text-center">Avatar</th>
									<th class="sorting1 text-center">Ngày đăng ký</th>
									<th class="sorting1 text-center">Trạng thái</th>
									<th class="sorting1 text-center">ID</th>
									<th class="sorting1 text-center">Xử lý</th>
								</tr>
								</thead>
								<tbody>
								@foreach( $news as $k => $item )
									<tr role="row" class="even" data-userId="{{ $item->id }}">
										<td class="text-center">{{$k+1}}</td>
										<td>
											<a href="<?php echo URL::to('/admin/user/'.$item->id);?>/edit">{{$item->name}}</a>
											@if($item->mobile) <br/>{{$item->mobile}} @endif
											@if($item->email) <br/>{{$item->email}} @endif
											@if($item->facebook_id)
												<br/><a href="{{ $item->facebook }}" target="_blank"><i class="btn btn-xs btn-primary fa fa-facebook"></i> {{ $item->facebook_id }}</a>
											@endif
										</td>
										<td>
											{{ $groups[$item->group] }}<br/>
										</td>
										<td>
											@if($item->avatar)
												<img src="<?php echo URL::to($item->avatar);?>" class="thumbnail" style="width: 50px; margin: 0px">
											@endif
										</td>
										<td class="text-center">
											{{ \App\Helper\StringHelper::date($item->created_at)  }}<br/>
											@if($item->promotion)
												Mã khuyến mại: <b>{{ $item->promotion }}</b>
											@endif
										</td>
										<td class="text-center">
											@if($item->status)
												<a href="#" class="btn btn-xs btn-success">Hoạt động</a>
											@else
												<a href="#" class="btn btn-xs btn-danger">Banned</a>
											@endif
										</td>
										<td class="text-center">{{$item->id}}</td>
										<td class="text-center">
											<a class="btn btn-success btn-xs" href="<?php echo URL::to('/admin/user/'.$item->id);?>/edit"><i class="fa fa-pencil"></i> Sửa</a>
											@if( Auth::user()->id != $item->id )
											<a onclick="return deleteItem({{$item->id}});" class="btn btn-danger btn-xs" href="#"><i class="fa fa-trash"></i> Xóa</a>
											
											<div class="btn-group" style="background: #e4e3e3;">
                                            <a target="_blank" href="/users/{{ $item->id }}/incognito" class="btn-info btn btn-xs" data-toggle="tooltip" title="Đăng nhập với tư cách là thành viên này!">
                                                <i class="fa fa-sign-in"></i> Login
                                            </a>
                                            <a href="/users/incognito/logout" data-toggle="modal" class="btn-info btn btn-xs" data-toggle="tooltip" title="Thoát tài khoản sử dụng thành viên này">
                                                <i class="fa fa-trash "></i> Logout
                                            </a>
                                        </div>
											@endif
										</td>
									</tr>
								@endforeach
								</tbody>
								<tfoot class="hidden">
								<tr>
									<th rowspan="1" colspan="1">Rendering engine</th>
									<th rowspan="1" colspan="1">Browser</th>
									<th rowspan="1" colspan="1">Platform(s)</th>
									<th rowspan="1" colspan="1">Engine version</th>
									<th rowspan="1" colspan="1">CSS grade</th>
								</tr>
								</tfoot>
							</table>
						</div>
					</div>
					<div class="row"><br/>
						<div class="col-sm-5">
							<div class="dataTables_length" id="example1_length">
								<label> Hiển thị
									<select onchange="this.form.submit();" name="limit" class="form-control input-sm">
										<option value="10">10</option>
										<option value="25">25</option>
										<option value="50">50</option>
										<option value="100">100</option>
									</select> mục
								</label>
							</div>
							<div class="dataTables_info hidden" id="example1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
						</div>
						<div class="col-sm-7">
							<div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
								{!! $news->appends(array('keyword' => app('request')->input('keyword')))->links() !!}
							</div>
						</div>
					</div>
				</div>
			</div>
		{!! Form::close() !!}
			<!-- /.box-body -->
		</div>
	</div>
</div>

<div class="hidden">
	<form action="{{ URL::route('user.destroy', '') }}" id="form_delete" method="POST">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
	</form>
</div>
<script type="text/javascript">
	function deleteItem(id){
		if ( confirm('Bạn có chắc chắn muốn xóa?') ) {
			$('#form_delete').attr('action', $('#form_delete').attr('action') + "/" + id);
			$('#form_delete').submit();
		}
		return false;
	}

    function update_avatar_fb(obj) {
        if ( confirm('Bạn có chắc chắn muốn cập nhật lại toàn bộ avatar cho user từ facebook (chỉ trường hợp ko tìm thấy ảnh trên server mới update)?') ) {
            $(obj).text('Đang cập nhật ...');
            var limit = $('select[name="limit"]').val();
            var submits_list_id = [];
            $('.dataTable tr[class="even"]').each(function(index, item){
                submits_list_id.push($(item).attr('data-userId'));
            });

            $.ajax({
                url: '/admin/user/update-fb-avatar',
                type: 'post',
                data: {users: submits_list_id},
                success: function(result) {
                    if(result.status == 1) {
                        alert('Cập nhật avatar user từ Facebook thành công');
                    } else {
                        alert('Cập nhật bị lỗi, xem log chi tiết lỗi kết quả trả về');
                    }

                    $(obj).text('Cập nhật img-submit');
                }
            });
        }
        return false;
    }
</script>
@stop

resources/views/admin/user/update-password.blade.php
@extends('admin.layouts.admin')

@section('breadcrum')
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Thay đổi mật khẩu
			<small>Thành viên</small>
		</h1>
		<ol class="breadcrumb hidden">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Thay đổi mật khẩu</li>
		</ol>
	</section>
	<style>
		.table label { font-weight: normal; }
	</style>
@stop

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<h3 class="box-title">Cập nhật mật khẩu mới</h3>
				</div>
  
				<div class="box-body">
					<form method="POST" name="" class="form-horizontal" action="">
						<input type="hidden" name="_token" value="{!! csrf_token() !!}">
						<div class="form-group">
	                        <label for="" class="col-sm-3 control-label required">Mật khẩu cũ</label>
	                        <div class="col-sm-9">
	                            {!! Form::password('password_old', array('class' => 'form-control', 'required')) !!}
	                        </div>
	                    </div>
	                    <div class="form-group">
	                        <label for="" class="col-sm-3 control-label required">Nhập mật khẩu mới</label>
	                        <div class="col-sm-9">
	                            {!! Form::password('password_new', array('class' => 'form-control', 'required')) !!}
	                        </div>        
	                    </div>
	                    <div class="form-group">
	                        <label for="" class="col-sm-3 control-label required">Nhắc lại mật khẩu mới</label>
	                        <div class="col-sm-9">
	                            {!! Form::password('password_new_retype', array('class' => 'form-control', 'required')) !!}
	                        </div>
	                    </div>
	                    <div class="form-group">
	                    	<label for="" class="col-sm-3 control-label required"></label>
	                    	<div class="col-sm-9">
	                        	<label><input checked="" type="checkbox" name="agree_change_password"/> Xác nhận thay đổi mật khẩu</label>
	                    	</div>
	                    </div>
	                    <div class="form-group">
	                        <label for="" class="col-sm-3 control-label"></label>
	                        <div class="col-sm-9">
	                            <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-send"></i> Hoàn tất</button>
	                        </div>
	                    </div>
                    </form>
				</div>
			</div>
		</div>
	</div>

@stop